<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use OpenApi\Attributes as OA;

#[OA\Schema(
    title: 'AddMembersRequest',
    required: ['application', 'applicationMembers'],
    properties: [
        new OA\Property(
            property: "application",
            required: ["accountHolderIdentityProofedIndicator"],
            properties: [
                new OA\Property(property: "accountHolderIdentityProofedIndicator", type: "boolean", description: "Indicates whether the account holder is identity proofed or not.")
            ],
            type: "object"
        ),
        new OA\Property(
            property: "applicationMembers",
            type: "array",
            items: new OA\Items(
                properties: [
                    new OA\Property(property: "requestingCoverageIndicator", description: "Indicates whether the member is applying for health coverage.", type: "boolean"),
                    new OA\Property(
                        property: "demographic",
                        required: ["birthDate"],
                        properties: [
                            new OA\Property(property: "ssn", description: "The member's attested Social Security Number.", type: "string"),
                            new OA\Property(property: "birthDate", description: "Member's attested birth date.", type: "string"),
                            new OA\Property(
                                property: "name",
                                description: "Member's primary name.",
                                required: ["firstName", "lastName"],
                                properties: [
                                    new OA\Property(property: "firstName", description: "The person's legal first name.", type: "string"),
                                    new OA\Property(property: "middleName", description: "Indicates the person's legal middle name or the person's legal middle initial.", type: "string"),
                                    new OA\Property(property: "lastName", description: "The person's legal last name.", type: "string"),
                                    new OA\Property(property: "suffix", description: "Indicates the personnel`s last name suffix, if there is one.", type: "string", enum: ["Jr.", "Sr.", "II", "III", "IV", "V"])
                                ],
                                type: "object"
                            ),
                            new OA\Property(
                                property: "ssnAlternateName",
                                properties: [
                                    new OA\Property(property: "firstName", description: "The person's legal first name.", type: "string"),
                                    new OA\Property(property: "middleName", description: "Indicates the person's legal middle name or the person's legal middle initial.", type: "string"),
                                    new OA\Property(property: "lastName", description: "The person's legal last name.", type: "string"),
                                    new OA\Property(property: "suffix", description: "Indicates the personnel`s last name suffix, if there is one.", type: "string", enum: ["Jr.", "Sr.", "II", "III", "IV", "V"])
                                ],
                                type: "object"
                            ),
                            new OA\Property(property: "sex", description: "A specific value intended to capture business meaning, indicating the person's gender.", type: "string", enum: ["MALE", "FEMALE"]),
                            new OA\Property(property: "maritalStatus", description: "Member's attested marital status.", type: "string", enum: ["UNMARRIED", "MARRIED"]),
                            new OA\Property(property: "noHomeAddressIndicator", description: "Indicates whether a member does not have a fixed address.", type: "boolean"),
                            new OA\Property(property: "liveOutsideStateTemporarilyIndicator", description: "Indicates whether this application member attests to living outside of the state temporarily.", type: "boolean"),
                            new OA\Property(property: "hispanicOriginIndicator", description: "An indication of whether a person has an ethnicity of Hispanic origin.", type: "boolean"),
                            new OA\Property(property: "americanIndianAlaskanNativeIndicator", description: "Indicates whether the member is American Indian or Alaskan Native.", type: "boolean"),
                            new OA\Property(
                                property: "ethnicity",
                                description: "The self-designated ethnic origin(s) of a person.",
                                type: "array",
                                items: new OA\Items(type: "string", enum: ["CUBAN", "MEXICAN", "PUERTO_RICAN", "OTHER"])
                            ),
                            new OA\Property(property: "otherEthnicityText", description: "Describes the actual ethnicity of the member if they selected `other` for ethnicity.", type: "string"),
                            new OA\Property(
                                property: "race",
                                description: "The self-declared designation of a racial legacy.",
                                type: "array",
                                items: new OA\Items(type: "string", enum: ["AMERICAN_INDIAN_OR_ALASKAN_NATIVE", "ASIAN_INDIAN", "BLACK_OR_AFRICAN_AMERICAN", "CHINESE", "FILIPINO", "GUAMANIAN_OR_CHAMORRO", "JAPANESE", "KOREAN", "NATIVE_HAWAIIAN", "OTHER_ASIAN", "OTHER_PACIFIC_ISLANDER", "SAMOAN", "VIETNAMESE", "WHITE", "OTHER"])
                            ),
                            new OA\Property(property: "otherRaceText", description: "Describes the actual race of the member if they selected `other` for Race.", type: "string"),
                            new OA\Property(property: "sexAssignedAtBirth", description: "Application member's attested sex assigned at birth.", type: "string", enum: ["MALE", "FEMALE", "OTHER", "PREFER_NOT_TO_ANSWER", "DONT_KNOW"]),
                            new OA\Property(property: "sexAssignedAtBirthOtherText", description: "Describes the actual sex assigned at birth of the member if they selected `other` for Sex Assigned At Birth.", type: "string"),
                            new OA\Property(property: "gender", description: "Application member's attested current gender identity.", type: "string", enum: ["MALE", "FEMALE", "TRANSGENDER_MALE", "TRANSGENDER_FEMALE", "DONT_KNOW", "DIFFERENT_TERM", "PREFER_NOT_TO_ANSWER"]),
                            new OA\Property(property: "genderDifferentTermText", description: "Describes the actual gender identity of the member if they selected `I use a different term` for Current Gender Identity.", type: "string"),
                            new OA\Property(property: "sexualOrientation", description: "Application member's attested current sexual orientation.", type: "string", enum: ["LESBIAN_OR_GAY", "STRAIGHT", "BISEXUAL", "DONT_KNOW", "DIFFERENT_TERM", "PREFER_NOT_TO_ANSWER"]),
                            new OA\Property(property: "sexualOrientationDifferentTermText", description: "Describes the actual sexual orientation of the member if they selected `I use a different term` for Current Sexual Orientation.", type: "string"),
                            new OA\Property(
                                property: "mailingAddress",
                                description: "The household contact's mailing address. Required for the primary contact if they do not have a Home address.",
                                required: ["streetName1", "cityName", "stateCode", "zipCode"],
                                properties: [
                                    new OA\Property(property: "streetName1", description: "The first line of the street address.", type: "string"),
                                    new OA\Property(property: "streetName2", description: "The second line of the street address.", type: "string"),
                                    new OA\Property(property: "cityName", description: "The name of the city where the address is located.", type: "string"),
                                    new OA\Property(property: "stateCode", description: "The state code.", type: "string", enum: ["AK", "AL", "AR", "AS", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "FM", "GA", "GU", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MH", "MI", "MN", "MO", "MP", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "PR", "PW", "RI", "SC", "SD", "TN", "TX", "UM", "UT", "VA", "VI", "VT", "WA", "WI", "WV", "WY"]),
                                    new OA\Property(property: "plus4Code", description: "The +4 code used in addition to zipCodes to identify a geographic segment.", type: "string"),
                                    new OA\Property(property: "zipCode", description: "The USPS identifier for a geographic area.", type: "string"),
                                    new OA\Property(property: "countyName", description: "County Name", type: "string"),
                                    new OA\Property(property: "countyFipsCode", description: "County Fips Code", type: "string")
                                ],
                                type: "object"
                            ),
                            new OA\Property(
                                property: "homeAddress",
                                description: "The member's home address.",
                                required: ["streetName1", "cityName", "stateCode", "zipCode"],
                                properties: [
                                    new OA\Property(property: "streetName1", description: "The first line of the street address.", type: "string"),
                                    new OA\Property(property: "streetName2", description: "The second line of the street address.", type: "string"),
                                    new OA\Property(property: "cityName", description: "The name of the city where the address is located.", type: "string"),
                                    new OA\Property(property: "stateCode", description: "The state code.", type: "string", enum: ["AK", "AL", "AR", "AS", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "FM", "GA", "GU", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MH", "MI", "MN", "MO", "MP", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "PR", "PW", "RI", "SC", "SD", "TN", "TX", "UM", "UT", "VA", "VI", "VT", "WA", "WI", "WV", "WY"]),
                                    new OA\Property(property: "plus4Code", description: "The +4 code used in addition to zipCodes to identify a geographic segment.", type: "string"),
                                    new OA\Property(property: "zipCode", description: "The USPS identifier for a geographic area.", type: "string"),
                                    new OA\Property(property: "countyName", description: "County Name", type: "string"),
                                    new OA\Property(property: "countyFipsCode", description: "County Fips Code", type: "string")
                                ],
                                type: "object"
                            ),
                            new OA\Property(
                                property: "transientAddress",
                                description: "The member's transient address.",
                                required: ["streetName1", "cityName", "stateCode", "zipCode"],
                                properties: [
                                    new OA\Property(property: "streetName1", description: "The first line of the street address.", type: "string"),
                                    new OA\Property(property: "streetName2", description: "The second line of the street address.", type: "string"),
                                    new OA\Property(property: "cityName", description: "The name of the city where the address is located.", type: "string"),
                                    new OA\Property(property: "stateCode", description: "The state code.", type: "string", enum: ["AK", "AL", "AR", "AS", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "FM", "GA", "GU", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MH", "MI", "MN", "MO", "MP", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "PR", "PW", "RI", "SC", "SD", "TN", "TX", "UM", "UT", "VA", "VI", "VT", "WA", "WI", "WV", "WY"]),
                                    new OA\Property(property: "plus4Code", description: "The +4 code used in addition to zipCodes to identify a geographic segment.", type: "string"),
                                    new OA\Property(property: "zipCode", description: "The USPS identifier for a geographic area.", type: "string"),
                                    new OA\Property(property: "countyName", description: "County Name", type: "string"),
                                    new OA\Property(property: "countyFipsCode", description: "County Fips Code", type: "string")
                                ],
                                type: "object"
                            ),
                        ],
                        type: "object"
                    )
                ],
                type: "object"
            )
        )
    ]
)]
class AddMembersRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'application.accountHolderIdentityProofedIndicator' => 'required|boolean',
            'applicationMembers.*.requestingCoverageIndicator' => 'boolean|nullable',
            'applicationMembers.*.demographic.ssn' => 'string|nullable',
            'applicationMembers.*.demographic.birthDate' => 'required|date',
            'applicationMembers.*.demographic.name.firstName' => 'required|string|max:255',
            'applicationMembers.*.demographic.name.lastName' => 'required|string|max:255',
            'applicationMembers.*.demographic.name.middleName' => 'nullable|string|max:255',
            'applicationMembers.*.demographic.name.suffix' => 'nullable|string|in:Jr.,Sr.,II,III,IV,V',
            'applicationMembers.*.demographic.ssnAlternateName.firstName' => 'nullable|string|max:255',
            'applicationMembers.*.demographic.ssnAlternateName.middleName' => 'nullable|string|max:255',
            'applicationMembers.*.demographic.ssnAlternateName.lastName' => 'nullable|string|max:255',
            'applicationMembers.*.demographic.ssnAlternateName.suffix' => 'nullable|string|in:Jr.,Sr.,II,III,IV,V',
            'applicationMembers.*.demographic.sex' => 'required|string|in:MALE,FEMALE',
            'applicationMembers.*.demographic.maritalStatus' => 'nullable|string|in:UNMARRIED,MARRIED',
            'applicationMembers.*.demographic.noHomeAddressIndicator' => 'boolean|nullable',
            'applicationMembers.*.demographic.liveOutsideStateTemporarilyIndicator' => 'boolean|nullable',
            'applicationMembers.*.demographic.hispanicOriginIndicator' => 'boolean|nullable',
            'applicationMembers.*.demographic.americanIndianAlaskanNativeIndicator' => 'boolean|nullable',
            'applicationMembers.*.demographic.ethnicity' => 'array|nullable',
            'applicationMembers.*.demographic.ethnicity.*' => 'string|in:CUBAN,MEXICAN,PUERTO_RICAN,OTHER',
            'applicationMembers.*.demographic.otherEthnicityText' => 'string|nullable',
            'applicationMembers.*.demographic.race' => 'array|nullable',
            'applicationMembers.*.demographic.race.*' => 'string|in:AMERICAN_INDIAN_OR_ALASKAN_NATIVE,ASIAN_INDIAN,BLACK_OR_AFRICAN_AMERICAN,CHINESE,FILIPINO,GUAMANIAN_OR_CHAMORRO,JAPANESE,KOREAN,NATIVE_HAWAIIAN,OTHER_ASIAN,OTHER_PACIFIC_ISLANDER,SAMOAN,VIETNAMESE,WHITE,OTHER',
            'applicationMembers.*.demographic.otherRaceText' => 'string|nullable',
            'applicationMembers.*.demographic.sexAssignedAtBirth' => 'string|nullable|in:MALE,FEMALE,OTHER,PREFER_NOT_TO_ANSWER,DONT_KNOW',
            'applicationMembers.*.demographic.sexAssignedAtBirthOtherText' => 'string|nullable',
            'applicationMembers.*.demographic.gender' => 'string|nullable|in:MALE,FEMALE,TRANSGENDER_MALE,TRANSGENDER_FEMALE,DONT_KNOW,DIFFERENT_TERM,PREFER_NOT_TO_ANSWER',
            'applicationMembers.*.demographic.genderDifferentTermText' => 'string|nullable',
            'applicationMembers.*.demographic.sexualOrientation' => 'string|nullable|in:LESBIAN_OR_GAY,STRAIGHT,BISEXUAL,DONT_KNOW,DIFFERENT_TERM,PREFER_NOT_TO_ANSWER',
            'applicationMembers.*.demographic.sexualOrientationDifferentTermText' => 'string|nullable',
            'applicationMembers.*.demographic.mailingAddress.streetName1' => 'required|string|max:255',
            'applicationMembers.*.demographic.mailingAddress.streetName2' => 'string|nullable|max:255',
            'applicationMembers.*.demographic.mailingAddress.cityName' => 'required|string|max:255',
            'applicationMembers.*.demographic.mailingAddress.stateCode' => 'required|string|in:AK,AL,AR,AS,AZ,CA,CO,CT,DC,DE,FL,FM,GA,GU,HI,IA,ID,IL,IN,KS,KY,LA,MA,MD,ME,MH,MI,MN,MO,MP,MS,MT,NC,ND,NE,NH,NJ,NM,NV,NY,OH,OK,OR,PA,PR,PW,RI,SC,SD,TN,TX,UM,UT,VA,VI,VT,WA,WI,WV,WY',
            'applicationMembers.*.demographic.mailingAddress.plus4Code' => 'string|nullable|max:10',
            'applicationMembers.*.demographic.mailingAddress.zipCode' => 'required|string|max:10',
            'applicationMembers.*.demographic.mailingAddress.countyName' => 'string|nullable|max:255',
            'applicationMembers.*.demographic.mailingAddress.countyFipsCode' => 'string|nullable|max:10',
            'applicationMembers.*.demographic.homeAddress.streetName1' => 'required|string|max:255',
            'applicationMembers.*.demographic.homeAddress.streetName2' => 'string|nullable|max:255',
            'applicationMembers.*.demographic.homeAddress.cityName' => 'required|string|max:255',
            'applicationMembers.*.demographic.homeAddress.stateCode' => 'required|string|in:AK,AL,AR,AS,AZ,CA,CO,CT,DC,DE,FL,FM,GA,GU,HI,IA,ID,IL,IN,KS,KY,LA,MA,MD,ME,MH,MI,MN,MO,MP,MS,MT,NC,ND,NE,NH,NJ,NM,NV,NY,OH,OK,OR,PA,PR,PW,RI,SC,SD,TN,TX,UM,UT,VA,VI,VT,WA,WI,WV,WY',
            'applicationMembers.*.demographic.homeAddress.plus4Code' => 'string|nullable|max:10',
            'applicationMembers.*.demographic.homeAddress.zipCode' => 'required|string|max:10',
            'applicationMembers.*.demographic.homeAddress.countyName' => 'string|nullable|max:255',
            'applicationMembers.*.demographic.homeAddress.countyFipsCode' => 'string|nullable|max:10',
            'applicationMembers.*.demographic.transientAddress.streetName1' => 'required|string|max:255',
            'applicationMembers.*.demographic.transientAddress.streetName2' => 'string|nullable|max:255',
            'applicationMembers.*.demographic.transientAddress.cityName' => 'required|string|max:255',
            'applicationMembers.*.demographic.transientAddress.stateCode' => 'required|string|in:AK,AL,AR,AS,AZ,CA,CO,CT,DC,DE,FL,FM,GA,GU,HI,IA,ID,IL,IN,KS,KY,LA,MA,MD,ME,MH,MI,MN,MO,MP,MS,MT,NC,ND,NE,NH,NJ,NM,NV,NY,OH,OK,OR,PA,PR,PW,RI,SC,SD,TN,TX,UM,UT,VA,VI,VT,WA,WI,WV,WY',
            'applicationMembers.*.demographic.transientAddress.plus4Code' => 'string|nullable|max:10',
            'applicationMembers.*.demographic.transientAddress.zipCode' => 'required|string|max:10',
            'applicationMembers.*.demographic.transientAddress.countyName' => 'string|nullable|max:255',
            'applicationMembers.*.demographic.transientAddress.countyFipsCode' => 'string|nullable|max:10',
            'applicationMembers.*.demographic.currentSchoolName' => 'string|nullable|max:255',
            'applicationMembers.*.demographic.currentSchoolGrade' => 'string|nullable|max:255',
            'applicationMembers.*.demographic.gradeJustCompleted' => 'string|nullable|max:255',
            'applicationMembers.*.demographic.mostRecentSchool' => 'string|nullable|max:255',
            'applicationMembers.*.demographic.mostRecentSchoolGrade' => 'string|nullable|max:255',
            'applicationMembers.*.demographic.mostRecentSchoolAttendanceDates' => 'array|nullable',
            'applicationMembers.*.demographic.mostRecentSchoolAttendanceDates.*.startDate' => 'date|nullable',
            'applicationMembers.*.demographic.mostRecentSchoolAttendanceDates.*.endDate' => 'date|nullable',
            'applicationMembers.*.demographic.languagePreference' => 'string|nullable|max:255',
            'applicationMembers.*.income.annualTaxIncome.incomeAmount' => 'nullable|numeric',
            'applicationMembers.*.income.annualTaxIncome.incomeLessExplainedIndicator' => 'nullable|boolean',
            'applicationMembers.*.income.annualTaxIncome.unknownIncomeIndicator' => 'nullable|boolean',
            'applicationMembers.*.income.annualTaxIncome.variableIncomeIndicator' => 'nullable|boolean',
            'applicationMembers.*.income.annualTaxIncome.receivedUnemploymentCompensationIndicator' => 'nullable|boolean',
            'applicationMembers.*.income.annualTaxIncome.taxHouseholdIncomeDiscrepancyDescriptionText' => 'nullable|string|max:255',
            'applicationMembers.*.income.annualTaxIncome.taxHouseholdIncomeDifferenceReasonType' => 'nullable|array',
            'applicationMembers.*.income.annualTaxIncome.taxHouseholdIncomeDifferenceReasonType.*' => 'nullable|string|max:255',
            'applicationMembers.*.income.annualTaxIncome.variableIncomeDescriptionText' => 'nullable|string|max:255',

            'applicationMembers.*.income.currentIncome.currentIncome1.incomeAmount' => 'nullable|numeric',
            'applicationMembers.*.income.currentIncome.currentIncome1.tribalIncomeAmount' => 'nullable|numeric',
            'applicationMembers.*.income.currentIncome.currentIncome1.incomeSourceType' => 'nullable|string|in:UNEMPLOYMENT,JOB,SOCIAL_SECURITY_BENEFIT,ALIMONY_PAYMENT,OTHER_INCOME,SELF_EMPLOYMENT,STUDENT_LOAN_INTEREST,RETIREMENT,CAPITAL_GAINS,INVESTMENT_INCOME,RENTAL_OR_ROYALTY_INCOME,FARMING_OR_FISHING_INCOME,PRIZES_AWARDS_GAMBLING_WINNINGS,ALIMONY_RECEIVED,OTHER_DEDUCTION,COURT_AWARDS,JURY_DUTY_PAY,CANCELED_DEBT,PENSION,CASH_SUPPORT,SCHOLARSHIP',
            'applicationMembers.*.income.currentIncome.currentIncome1.incomeFrequencyType' => 'nullable|string|in:WEEKLY,BI_WEEKLY,MONTHLY,QUARTERLY,ANNUALLY,SEMI_MONTHLY,HOURLY,ONE_TIME,DAILY',
            'applicationMembers.*.income.currentIncome.currentIncome1.estimatedForAptcIndicator' => 'nullable|boolean',
            'applicationMembers.*.income.currentIncome.currentIncome1.jobIncome.averageWeeklyWorkDays' => 'nullable|numeric',
            'applicationMembers.*.income.currentIncome.currentIncome1.jobIncome.averageWeeklyWorkHours' => 'nullable|numeric',
            'applicationMembers.*.income.currentIncome.currentIncome1.jobIncome.incomeDifferenceReason' => 'nullable|string|in:STOP_WORKING,DECREASE_HOURS,CHANGE_JOBS,WAGE_CUT,OTHER',
            'applicationMembers.*.income.currentIncome.currentIncome1.jobIncome.employerName' => 'nullable|string|max:255',
            'applicationMembers.*.income.currentIncome.currentIncome1.jobIncome.otherIncomeDifferenceReason' => 'nullable|string|max:255',
            'applicationMembers.*.income.currentIncome.currentIncome1.otherDeductionDescription' => 'nullable|string|max:255',
            'applicationMembers.*.income.currentIncome.currentIncome1.selfEmploymentIncomeDescription' => 'nullable|string|max:255',
            'applicationMembers.*.income.currentIncome.currentIncome1.unemploymentIncome.expirationDate' => 'nullable|date',
            'applicationMembers.*.income.currentIncome.currentIncome1.unemploymentIncome.incomeDescription' => 'nullable|string|max:255',
            'applicationMembers.*.income.currentIncome.currentIncome1.incomeFederallyRestrictedIndicator' => 'nullable|boolean',
            'applicationMembers.*.income.currentIncome.currentIncome1.otherIncomeDescription' => 'nullable|string|max:255',
            'applicationMembers.*.family.liveWithParentOrSiblingIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.babyDueQuantity' => 'nullable|numeric|min:1',
            'applicationMembers.*.family.taxDependentIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.taxFilerIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.taxReturnFilingStatusType' => 'nullable|string|in:SINGLE_FILER,MARRIED_FILING_JOINTLY,MARRIED_FILING_SEPARATELY,HEAD_OF_HOUSEHOLD',
            'applicationMembers.*.family.claimsDependentIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.claimingTaxFilerNotOnApplicationIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.livesWithCustodialParentNotOnApplicationIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.fosterCareIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.fosterCareEndAge' => 'nullable|numeric|min:0',
            'applicationMembers.*.family.medicaidDuringFosterCareIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.fosterCareState' => 'nullable|string|in:AK,AL,AR,AS,AZ,CA,CO,CT,DC,DE,FL,FM,GA,GU,HI,IA,ID,IL,IN,KS,KY,LA,MA,MD,ME,MH,MI,MN,MO,MP,MS,MT,NC,ND,NE,NH,NJ,NM,NV,NY,OH,OK,OR,PA,PR,PW,RI,SC,SD,TN,TX,UM,UT,VA,VI,VT,WA,WI,WV,WY',
            'applicationMembers.*.family.medicaidFamilyNotProvidedIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.taxFilerNotProvidedIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.parentCaretakerIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.pregnancyIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.fullTimeStatusIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.studentsParentLivingInExchangeStateIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.parentLivesInStudentStateIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.absentParentIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.resideWithBothParentIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.attestedHeadOfHouseholdIndicator' => 'nullable|boolean',
            'applicationMembers.*.family.liveApartFromSpouseIndicator' => 'nullable|boolean',

            'applicationMembers.*.lawfulPresence.lawfulPresenceGrantDate' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceStatusIndicator' => 'nullable|boolean',
            'applicationMembers.*.lawfulPresence.livedInUs5yearIndicator' => 'nullable|boolean',
            'applicationMembers.*.lawfulPresence.noAlienNumberIndicator' => 'nullable|boolean',
            'applicationMembers.*.lawfulPresence.citizenshipIndicator' => 'nullable|boolean',
            'applicationMembers.*.lawfulPresence.naturalizedCitizenIndicator' => 'nullable|boolean',

            // PERMANENT_RESIDENT_CARD_I_551
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.documentExpirationDate' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.alienNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.employmentAuthorizationCategoryIdentifier' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.sevisId' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.i94Number' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.passportNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.passportIssuingCountry' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.cardNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.naturalizationCertificateNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.citizenshipNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.documentAlternateName.firstName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.documentAlternateName.middleName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.documentAlternateName.lastName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.documentAlternateName.suffix' => 'nullable|string|in:Jr.,Sr.,II,III,IV,V',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.noIdentifiersProvidedIndicator' => 'nullable|boolean',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.PERMANENT_RESIDENT_CARD_I_551.otherTypeText' => 'nullable|string',

            // TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.documentExpirationDate' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.alienNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.employmentAuthorizationCategoryIdentifier' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.sevisId' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.i94Number' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.passportNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.passportIssuingCountry' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.cardNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.naturalizationCertificateNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.citizenshipNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.documentAlternateName.firstName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.documentAlternateName.middleName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.documentAlternateName.lastName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.documentAlternateName.suffix' => 'nullable|string|in:Jr.,Sr.,II,III,IV,V',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.noIdentifiersProvidedIndicator' => 'nullable|boolean',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.TEMPORARY_I_551_STAMP_ON_PASSPORT_OR_I_94_I_94A.otherTypeText' => 'nullable|string',

            // MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.documentExpirationDate' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.alienNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.employmentAuthorizationCategoryIdentifier' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.sevisId' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.i94Number' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.passportNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.passportIssuingCountry' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.cardNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.naturalizationCertificateNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.citizenshipNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.documentAlternateName.firstName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.documentAlternateName.middleName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.documentAlternateName.lastName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.documentAlternateName.suffix' => 'nullable|string|in:Jr.,Sr.,II,III,IV,V',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.noIdentifiersProvidedIndicator' => 'nullable|boolean',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.MACHINE_READABLE_IMMIGRANT_VISA_WITH_TEMPORARY_I_551_LANGUAGE.otherTypeText' => 'nullable|string',

            // EMPLOYMENT_AUTHORIZATION_CARD_I_766
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.documentExpirationDate' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.alienNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.employmentAuthorizationCategoryIdentifier' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.sevisId' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.i94Number' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.passportNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.passportIssuingCountry' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.cardNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.naturalizationCertificateNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.citizenshipNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.documentAlternateName.firstName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.documentAlternateName.middleName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.documentAlternateName.lastName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.documentAlternateName.suffix' => 'nullable|string|in:Jr.,Sr.,II,III,IV,V',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.noIdentifiersProvidedIndicator' => 'nullable|boolean',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.EMPLOYMENT_AUTHORIZATION_CARD_I_766.otherTypeText' => 'nullable|string',

            // ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.documentExpirationDate' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.alienNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.employmentAuthorizationCategoryIdentifier' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.sevisId' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.i94Number' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.passportNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.passportIssuingCountry' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.cardNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.naturalizationCertificateNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.citizenshipNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.documentAlternateName.firstName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.documentAlternateName.middleName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.documentAlternateName.lastName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.documentAlternateName.suffix' => 'nullable|string|in:Jr.,Sr.,II,III,IV,V',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.noIdentifiersProvidedIndicator' => 'nullable|boolean',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_FOREIGN_PASSPORT_I_94.otherTypeText' => 'nullable|string',

            // ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.documentExpirationDate' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.alienNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.employmentAuthorizationCategoryIdentifier' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.sevisId' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.i94Number' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.passportNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.passportIssuingCountry' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.cardNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.naturalizationCertificateNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.citizenshipNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.documentAlternateName.firstName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.documentAlternateName.middleName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.documentAlternateName.lastName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.documentAlternateName.suffix' => 'nullable|string|in:Jr.,Sr.,II,III,IV,V',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.noIdentifiersProvidedIndicator' => 'nullable|boolean',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.ARRIVAL_DEPARTURE_RECORD_IN_UNEXPIRED_FOREIGN_PASSPORT_I_94.otherTypeText' => 'nullable|string',

            // FOREIGN_PASSPORT
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.documentExpirationDate' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.alienNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.employmentAuthorizationCategoryIdentifier' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.sevisId' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.i94Number' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.passportNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.passportIssuingCountry' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.cardNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.naturalizationCertificateNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.citizenshipNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.documentAlternateName.firstName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.documentAlternateName.middleName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.documentAlternateName.lastName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.documentAlternateName.suffix' => 'nullable|string|in:Jr.,Sr.,II,III,IV,V',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.noIdentifiersProvidedIndicator' => 'nullable|boolean',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.FOREIGN_PASSPORT.otherTypeText' => 'nullable|string',

            // REENTRY_PERMIT
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.documentExpirationDate' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.alienNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.employmentAuthorizationCategoryIdentifier' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.sevisId' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.i94Number' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.passportNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.passportIssuingCountry' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.cardNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.naturalizationCertificateNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.citizenshipNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.documentAlternateName.firstName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.documentAlternateName.middleName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.documentAlternateName.lastName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.documentAlternateName.suffix' => 'nullable|string|in:Jr.,Sr.,II,III,IV,V',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.noIdentifiersProvidedIndicator' => 'nullable|boolean',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REENTRY_PERMIT.otherTypeText' => 'nullable|string',

            // REFUGEE_TRAVEL_DOCUMENT
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.documentExpirationDate' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.alienNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.employmentAuthorizationCategoryIdentifier' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.sevisId' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.i94Number' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.passportNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.passportIssuingCountry' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.cardNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.naturalizationCertificateNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.citizenshipNumber' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.documentAlternateName.firstName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.documentAlternateName.middleName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.documentAlternateName.lastName' => 'nullable|string',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.documentAlternateName.suffix' => 'nullable|string|in:Jr.,Sr.,II,III,IV,V',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.noIdentifiersProvidedIndicator' => 'nullable|boolean',
            'applicationMembers.*.lawfulPresence.lawfulPresenceDocumentation.REFUGEE_TRAVEL_DOCUMENT.otherTypeText' => 'nullable|string',

            'applicationMembers.*.insuranceCoverage.enrolledInIchraIndicator' => 'nullable|boolean',
            'applicationMembers.*.insuranceCoverage.offeredIchraIndicator' => 'nullable|boolean',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.hraType' => 'nullable|string|in:ICHRA,QSEHRA',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.startDate' => 'nullable|date_format:Y-m-d',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.noticeDate' => 'nullable|date_format:Y-m-d',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.enrolledInOfferFromSameEmployerIndicator' => 'nullable|boolean',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.enrolledInOfferFromSameEmployerUntilStartDateIndicator' => 'nullable|boolean',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.primaryInsuredMemberIdentifier' => 'nullable|string|max:255',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.endDate' => 'nullable|date_format:Y-m-d|after_or_equal:applicationMembers.*.insuranceCoverage.hraOffers.*.startDate',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employeeSelfOnlyOfferAmount' => 'nullable|numeric|min:0',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employeeSelfOnlyOfferFrequencyType' => 'nullable|string|in:WEEKLY,BI_WEEKLY,MONTHLY,QUARTERLY,ANNUALLY,SEMI_MONTHLY,PRORATED',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.primaryInsuredMemberNotInTaxHhIndicator' => 'nullable|boolean',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.name' => 'nullable|string|max:255',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.employerIdentificationNumber' => 'nullable|string|max:255',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.streetName1' => 'nullable|string|max:255',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.streetName2' => 'nullable|string|max:255',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.cityName' => 'nullable|string|max:255',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.stateCode' => 'nullable|string|in:AK,AL,AR,AS,AZ,CA,CO,CT,DC,DE,FL,FM,GA,GU,HI,IA,ID,IL,IN,KS,KY,LA,MA,MD,ME,MH,MI,MN,MO,MP,MS,MT,NC,ND,NE,NH,NJ,NM,NV,NY,OH,OK,OR,PA,PR,PW,RI,SC,SD,TN,TX,UM,UT,VA,VI,VT,WA,WI,WV,WY',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.zipCode' => 'nullable|string|max:10',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.plus4Code' => 'nullable|string|max:4',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.countryCode' => 'nullable|string|max:3',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.countyName' => 'nullable|string|max:255',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.countyFipsCode' => 'nullable|string|max:255',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.employerPhoneNumber' => 'nullable|string|regex:/^\+?\d{1,15}$/',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.contact.name.firstName' => 'nullable|string|max:100',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.contact.name.middleName' => 'nullable|string|max:100',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.contact.name.lastName' => 'nullable|string|max:100',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.contact.name.suffix' => 'nullable|string|in:Jr.,Sr.,II,III,IV,V',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.contact.email' => 'nullable|string|email|max:255',
            'applicationMembers.*.insuranceCoverage.hraOffers.*.employer.contact.phoneNumber' => 'nullable|string|regex:/^\+?\d{1,15}$/',

            'applicationMembers.*.insuranceCoverage.enrolledCoverages.*.insuranceMarketType' => 'nullable|string|in:MEDICARE,MEDICAID,CHIP,TRICARE,VETERAN_HEALTH_PROGRAM,PEACE_CORPS,INDIVIDUAL_INSURANCE,MARKETPLACE_COVERAGE,NONE',
            'applicationMembers.*.insuranceCoverage.enrolledCoverages.*.insurancePolicyMemberId' => 'nullable|string|max:255',
            'applicationMembers.*.insuranceCoverage.enrolledCoverages.*.insurancePolicyNumber' => 'nullable|string|max:255',
            'applicationMembers.*.insuranceCoverage.enrolledCoverages.*.insurancePlanName' => 'nullable|string|max:255',

            'applicationMembers.*.insuranceCoverage.offeredEmployeeCoverage' => 'nullable|string|in:YES,NO,NOT_APPLICABLE,I_DONT_KNOW',

            'applicationMembers.*.medicaid.medicaidDeniedDate' => 'nullable|date_format:Y-m-d',
            'applicationMembers.*.medicaid.medicaidDeniedDueToImmigrationIndicator' => 'nullable|boolean',
            'applicationMembers.*.medicaid.medicaidDeniedIndicator' => 'nullable|boolean',
            'applicationMembers.*.medicaid.parent1WeeklyWorkHourQuantity' => 'nullable|numeric|min:0',
            'applicationMembers.*.medicaid.parent2WeeklyWorkHourQuantity' => 'nullable|numeric|min:0',
            'applicationMembers.*.medicaid.unpaidBillIndicator' => 'nullable|boolean',
            'applicationMembers.*.medicaid.coveredDependentChildIndicator' => 'nullable|boolean',
            'applicationMembers.*.medicaid.enrolledInHealthCoverageIndicator' => 'nullable|boolean',
            'applicationMembers.*.medicaid.insuranceCoverage.*.insurancePolicyMemberId' => 'required|string|max:255',
            'applicationMembers.*.medicaid.insuranceCoverage.*.insurancePolicyNumber' => 'required|string|max:255',
            'applicationMembers.*.medicaid.insuranceCoverage.*.insurancePlanName' => 'required|string|max:255',
            'applicationMembers.*.medicaid.insuranceCoverage.*.insuranceMarketType' => 'required|string|in:MEDICARE,MEDICAID,CHIP,TRICARE,PEACE_CORPS,VETERAN_HEALTH_PROGRAM,OTHER_FULL_BENEFIT_COVERAGE,OTHER_LIMITED_BENEFIT_COVERAGE,EMPLOYER_SPONSORED,MARKETPLACE_COVERAGE,TRICARE',
            'applicationMembers.*.medicaid.informationChangeSinceMedicaidDeniedIndicator' => 'nullable|boolean',
            'applicationMembers.*.medicaid.immigrationStatusFiveYearIndicator' => 'nullable|boolean',
            'applicationMembers.*.medicaid.immigrationStatusChangeSinceDeniedIndicator' => 'nullable|boolean',
            'applicationMembers.*.medicaid.informationChangeSinceMedicaidEndedIndicator' => 'nullable|boolean',
            'applicationMembers.*.medicaid.medicaidEndIndicator' => 'nullable|boolean',
            'applicationMembers.*.medicaid.medicaidEndDate' => 'nullable|date_format:Y-m-d',

            'applicationMembers.*.chip.coverageEndedIndicator' => 'nullable|boolean',
            'applicationMembers.*.chip.stateHealthBenefitIndicator' => 'nullable|boolean',
            'applicationMembers.*.chip.coverageEndedReasonType' => 'nullable|string|in:PARENT_NO_LONGER_WORKS_FOR_THE_COMPANY,COMPANY_STOPPED_OFFERING_INSURANCE,COMPANY_STOPPED_OFFERING_INSURANCE_TO_DEPENDENTS,INSURANCE_TOO_EXPENSIVE,MEDICAL_NEEDS_NOT_COVERED,OTHER',
            'applicationMembers.*.chip.coverageEndedReasonText' => 'nullable|string|max:255',

            'applicationMembers.*.nonMagi.blindOrDisabledIndicator' => 'nullable|boolean',
            'applicationMembers.*.nonMagi.longTermCareIndicator' => 'nullable|boolean',

            'applicationMembers.*.other.appliedDuringOeOrLifeChangeIndicator' => 'nullable|boolean',

            'applicationMembers.*.other.changeInCircumstance.GAINING_LAWFUL_PRESENCE.changeDate' => 'nullable|date_format:Y-m-d',
            'applicationMembers.*.other.changeInCircumstance.RELEASE_FROM_INCARCERATION.changeDate' => 'nullable|date_format:Y-m-d',
            'applicationMembers.*.other.changeInCircumstance.LOSS_OF_MEC.changeDate' => 'nullable|date_format:Y-m-d',
            'applicationMembers.*.other.changeInCircumstance.LOSS_OF_MEC.lossMecIssuerName' => 'nullable|string|max:255',
            'applicationMembers.*.other.changeInCircumstance.FUTURE_LOSS_OF_MEC.changeDate' => 'nullable|date_format:Y-m-d',
            'applicationMembers.*.other.changeInCircumstance.FUTURE_LOSS_OF_MEC.lossMecIssuerName' => 'nullable|string|max:255',
            'applicationMembers.*.other.changeInCircumstance.RELOCATION.changeDate' => 'nullable|date_format:Y-m-d',
            'applicationMembers.*.other.changeInCircumstance.RELOCATION.movedFromForeignCountryIndicator' => 'nullable|boolean',
            'applicationMembers.*.other.changeInCircumstance.RELOCATION.coverage60DayBeforeMoveIndicator' => 'nullable|boolean',
            'applicationMembers.*.other.changeInCircumstance.RELOCATION.precedingZipCode' => 'nullable|string|max:10',
            'applicationMembers.*.other.changeInCircumstance.RELOCATION.precedingStateCode' => 'nullable|string|size:2',
            'applicationMembers.*.other.changeInCircumstance.RELOCATION.precedingCountyName' => 'nullable|string|max:255',
            'applicationMembers.*.other.changeInCircumstance.MARRIAGE.changeDate' => 'nullable|date_format:Y-m-d',
            'applicationMembers.*.other.changeInCircumstance.MARRIAGE.coverage60DayBeforeMarriageIndicator' => 'nullable|boolean',
            'applicationMembers.*.other.changeInCircumstance.MARRIAGE.liveInForeignCountry60DayBeforeMarriageIndicator' => 'nullable|boolean',
            'applicationMembers.*.other.changeInCircumstance.ADOPTION.changeDate' => 'nullable|date_format:Y-m-d',

            'applicationMembers.*.other.americanIndianAlaskanNative.federallyRecognizedTribeName' => 'nullable|string|max:255',
            'applicationMembers.*.other.americanIndianAlaskanNative.personRecognizedTribeIndicator' => 'nullable|boolean',
            'applicationMembers.*.other.americanIndianAlaskanNative.receiveItuIndicator' => 'nullable|boolean',
            'applicationMembers.*.other.americanIndianAlaskanNative.eligibleForItuIndicator' => 'nullable|boolean',

            'applicationMembers.*.other.veteranIndicator' => 'nullable|boolean',

            'applicationMembers.*.other.incarcerationType' => 'nullable|string|in:NOT_INCARCERATED,PENDING_DISPOSITION,INCARCERATED',

            'applicationMembers.*.other.reconcilePtcIndicatorType' => 'nullable|string|in:TRUE,NOT_APPLICABLE',

            'applicationMembers.*.other.veteranSelfIndicator' => 'nullable|boolean',

            'applicationMembers.*.other.nonMemberVeteranRelationshipTypes' => 'nullable|array',
        ];
    }
}
